import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "@/context/Providers";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ["100", "200", "300", "400", "500", "600", "900"],
  fontFamily: "Poppins",
  fontDisplay: "swap",
  fontStyle: "sans-serif",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
